### ISSUE TITLE
On-premise endpoint: UNABLE_TO_VERIFY_LEAF_SIGNATURE 

### ISSUE THREAD

**Issue by brighterdevelopment** [Vizzuality/cartodb-nodejs#35]
We are tryingto use Busla's forked version to query our on-premise CartoDB instance at https://cartodb.brighterdevelopment.com

We tried a very simple test:

'use strict';
var CartoDB = require('cartodb');
exports.init = function(req, res){
	var client = new CartoDB({user:"demo-admin",cartodb_url:"https://cartodb.brighterdevelopment.com", api_key:"OUR_API_KEY_GOES_HERE"});
	var outputRows = function(err, data) {
	 //  do something
	};
	client.on('connect', function() {
	  client
	  .query("select * from {table} limit 5", {table: 'ne_10m_populated_places_simple'}, outputRows)
	});
	client.connect();
};

NOTE: we also tested with the alternative parameter, "api_url", via the Master branch of cartodb-nodejs

We receive this error:

Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
    at SecurePair.<anonymous> (tls.js:1367:32)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:979:10)
    at CleartextStream.read [as _read] (tls.js:471:13)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.write [as _write] (tls.js:368:25)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at EncryptedStream.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)

Any help would be HUGELY appreciated.
Our goals is to query our on premise-instance via https.
We are open to any / all approaches.

Thank you!

**Comment by busla** [comment]
This is what I found.
http://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature

Looks like an SSL issue on your server.

**Comment by busla** [comment]
Looks like your SSL is self-signed. You might want to get an authenticated cert.
https://www.sslshopper.com/ssl-checker.html#hostname=brighterdevelopment.com

This one suggests turning off `strict-ssl` by changing this env:
http://stackoverflow.com/questions/18461979/node-js-error-with-ssl-unable-to-verify-leaf-signature
`process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';`

Probably not a good idea unless your playing around.


Here is another solution you might want to look at that doesn ´t force you to turn off SSL:
http://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature/22263280#22263280

**Comment by brighterdevelopment** [comment]
Thanks for looking into this. The SSL CERT is actually not self signed. However I will follow up with some of these suggested fixes and let you know what works
